### ISSUE TITLE
Feedback is automatically sorted oldest to newest; should also be sortable newest to oldest

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan_feedback#23]
As a Site Manager on a DKAN site using the Feedback module, I want to easily view the latest feedback that has been submitted.

However, Feedback is sorted oldest-to-newest by default. This means that to view the newest Feedback, I have to skip ahead to the very last page.

Acceptance criteria: Can sort Feedback by date added.

**Comment by janette** [comment]
fixed by #25
